Lenny
tvtri96/indoor-navigation pull request #11
Opened 2017-06-07 12:21 UTC by leenderteloff

please look at the buttonPress function case exitButton

2017-06-07 12:48 UTC, tvtri96 commented
Resolve the conflict before making the PR. And if it is not complete, don't make a PR.

2017-06-07 12:55 UTC, vaguelycompetent commented
Yeah since we dont know how to merge with conflicts in SourceTree or in the shell this was the easiest way to do it

2017-06-07 18:45 UTC, henrycity requested changes

2017-06-07 18:45 UTC, tvtri96 commented on MobileDevProject/ViewController.swift
> +
Don't make unnecessary changes!

2017-06-07 18:45 UTC, tvtri96 commented on MobileDevProject/ViewController.swift
> +
Check the linter before commiting.

2017-06-07 18:45 UTC, tvtri96 commented on MobileDevProject/ViewController.swift
> +<<<<<<< .merge_file_iRmVcJ
what is this?

2017-06-07 18:45 UTC, tvtri96 commented on MobileDevProject/ViewController.swift
> +>>>>>>> .merge_file_hMsxl8
again?

2017-06-07 18:45 UTC, tvtri96 commented on MobileDevProject/ViewController.swift
> +=======
?

2017-06-13 09:45 UTC, leenderteloff commented on MobileDevProject/ViewController.swift
> +>>>>>>> .merge_file_hMsxl8
wtf... All the things you comment on are not in my project..

2017-06-13 09:51 UTC, vaguelycompetent commented on MobileDevProject/ViewController.swift
> +>>>>>>> .merge_file_hMsxl8
Possibly an issue with the webmerge I did, try pull and see if theres a change

2017-06-14 10:12 UTC, closed without merging