Feature/rotating compass
tvtri96/indoor-navigation pull request #4
Opened 2017-05-23 13:19 UTC by tvtri96

Add a compass on top of the map image. The compass will be invisible if the map starts to rotate. If the map doesn't rotate, the compass will rotate.

TODO: Refractor code for rotating the compass and map.

2017-05-23 13:53 UTC, danielcwilson requested changes
Reduce redundancy and change the variable names

2017-05-23 14:58 UTC, tvtri96 commented
Add switch and change variable name

2017-05-24 08:41 UTC, danielcwilson approved these changes

2017-05-24 08:42 UTC, vaguelycompetent commented
I can't see any issues but I also can't test it; although I assume you have

2017-05-24 09:08 UTC, merged